name: Build and Deploy Boot & Vue

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ----------------------- 构建 Vue 前端 -----------------------
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and build Vue
        run: |
          cd blog-vue
          npm ci --prefer-offline
          npm run build

      # ----------------------- 构建 Spring Boot 后端 -----------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot
        run: |
          cd blog-boot
          chmod +x mvnw
          ./mvnw clean package -DskipTests -DfinalName=blog-boot
          ls -l target/ # 验证构建产物

      # ----------------------- 部署 Vue 到服务器 -----------------------
      - name: Deploy Vue
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }} 
          port: 22
          source: "blog-vue/dist/"
          target: "/opt/1panel/apps/openresty/openresty/html/blog"
          rm: true
          strip_components: 1

      # ----------------------- 部署 Spring Boot 到服务器 -----------------------
      - name: Deploy Spring Boot
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "blog-boot/target/blog-boot.jar"
          target: "/home/java/blog/blog-boot/"
          rm: true

      # ----------------------- 重启 Spring Boot 服务 -----------------------
      - name: Restart Spring Boot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/java/blog/blog-boot
            chmod +x blog-boot.sh
            ./blog-boot.sh
            sleep 5
            pgrep -f blog-boot.jar || echo "Process start failed"